<a href="https://colab.research.google.com/github/Ajay-user/DataScience/blob/master/Notes/TensorFlow_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import numpy as np
import tensorflow as tf
# https://www.tensorflow.org/guide/tensor

## TensorFlow tensor

* Tensors are multi-dimensional arrays with a uniform type (called a dtype).

* Tensors are (kind of) like np.arrays.

* All tensors are immutable like Python numbers and strings: you can never update the contents of a tensor, only create a new one.

In [4]:
# rank 0 tensor
# This will be an int32 tensor by default; see "dtypes" below.
rank_0_tensor = tf.constant(101)
print(rank_0_tensor)

tf.Tensor(101, shape=(), dtype=int32)


A "vector" or "rank-1" tensor is like a list of values. A vector has one axis:

In [6]:
# rank 1 tensor
# list of values 
rank_1_tensor = tf.constant([1,2,3])
print(rank_1_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


A "matrix" or "rank-2" tensor has two axes:

In [8]:
# we can be specifict about the dtype
rank_2_tensor = tf.constant([[1,2,3],[4,5,6]], dtype='float32')
print(rank_2_tensor)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


Tensors may have more axes; here is a tensor with three axes:

In [9]:
# there can be an arbitary number of axes (also called as dimensions)
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


There are many ways you might visualize a tensor with more than two axes.

<img src="https://www.tensorflow.org/guide/images/tensor/3-axis_numpy.png"/>
<img src="https://www.tensorflow.org/guide/images/tensor/3-axis_front.png"/>
<img src="https://www.tensorflow.org/guide/images/tensor/3-axis_block.png"/>

You can convert a tensor to a NumPy array either using np.array or the tensor.numpy method:

In [12]:
print(rank_2_tensor.numpy())

[[1. 2. 3.]
 [4. 5. 6.]]


You can do basic math on tensors, including addition, element-wise multiplication, and matrix multiplication.

In [19]:
a = tf.ones((2,2))
b = tf.ones((2,2))*2

print('Tensor a \n' , a)
print('Tensor b \n' , b)

Tensor a 
 tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
Tensor b 
 tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)


In [20]:
print('addition a + b \n', tf.add(a, b))
print('substract a - b  \n', tf.subtract(a, b))
print('multiply elementwise a * b \n', tf.multiply(a, b))
print('matrix multiply a @ b \n', tf.matmul(a, b))

addition a + b 
 tf.Tensor(
[[3. 3.]
 [3. 3.]], shape=(2, 2), dtype=float32)
substract a - b  
 tf.Tensor(
[[-1. -1.]
 [-1. -1.]], shape=(2, 2), dtype=float32)
multiply elementwise a * b 
 tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)
matrix multiply a @ b 
 tf.Tensor(
[[4. 4.]
 [4. 4.]], shape=(2, 2), dtype=float32)


In [23]:
# Tensors are used in all kinds of operations (ops).


c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

# Find the largest value
print('Find the largest value \n',tf.reduce_max(c))
# Find the index of the largest value
print('Find the index of the largest value \n',tf.argmax(c))
# Compute the softmax
print('Compute the softmax \n',tf.nn.softmax(c))

Find the largest value 
 tf.Tensor(10.0, shape=(), dtype=float32)
Find the index of the largest value 
 tf.Tensor([1 0], shape=(2,), dtype=int64)
Compute the softmax 
 tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


## shapes
**Tensors have shapes**.

**Shape**: The length (number of elements) of each of the axes of a tensor.

**Rank**: Number of tensor axes. A scalar has rank 0, a vector has rank 1, a matrix is rank 2.

**Axis or Dimension**: A particular dimension of a tensor.

**Size**: The total number of items in the tensor, the product shape vector.

In [33]:
rank_4_tensor = tf.zeros([3,2,4,5])


print('Shape of tensor is ', rank_4_tensor.shape)
print('Type of elements in tensor is ', rank_4_tensor.dtype)
print('Number of axes ', rank_4_tensor.ndim)
print('Elements along axis 0 of tensor',rank_4_tensor.shape[0])
print('Elements along axis -1 ( last axis ) of tensor',rank_4_tensor.shape[-1])
print('Size of tensor ( product of shape vector )', tf.size(rank_4_tensor).numpy())

Shape of tensor is  (3, 2, 4, 5)
Type of elements in tensor is  <dtype: 'float32'>
Number of axes  4
Elements along axis 0 of tensor 3
Elements along axis -1 ( last axis ) of tensor 5
Size of tensor ( product of shape vector ) 120


While axes are often referred to by their indices, you should always keep track of the meaning of each. Often axes are ordered from global to local: **The batch axis first, followed by spatial dimensions, and features for each location last**. This way feature vectors are contiguous regions of memory.

<img src="https://www.tensorflow.org/guide/images/tensor/shape2.png" />

## Indexing
**Single-axis indexing**

TensorFlow follows standard Python indexing rules, similar to indexing a list or a string in Python, and the basic rules for NumPy indexing.

* indexes start at 0
* negative indices count backwards from the end
* colons, :, are used for slices: start:stop:step

In [35]:
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(rank_1_tensor.numpy())
# Indexing with a scalar removes the axis:
print("First:", rank_1_tensor[0].numpy())
print("Second:", rank_1_tensor[1].numpy())
print("Last:", rank_1_tensor[-1].numpy())
# Indexing with a : slice keeps the axis:
print("Everything:", rank_1_tensor[:].numpy())
print("Before 4:", rank_1_tensor[:4].numpy())
print("From 4 to the end:", rank_1_tensor[4:].numpy())
print("From 2, before 7:", rank_1_tensor[2:7].numpy())
print("Every other item:", rank_1_tensor[::2].numpy())
print("Reversed:", rank_1_tensor[::-1].numpy())

[ 0  1  1  2  3  5  8 13 21 34]
First: 0
Second: 1
Last: 34
Everything: [ 0  1  1  2  3  5  8 13 21 34]
Before 4: [0 1 1 2]
From 4 to the end: [ 3  5  8 13 21 34]
From 2, before 7: [1 2 3 5 8]
Every other item: [ 0  1  3  8 21]
Reversed: [34 21 13  8  5  3  2  1  1  0]


**Multi-axis indexing**

Higher rank tensors are indexed by passing multiple indices.

The exact same rules as in the single-axis case apply to each axis independently.

In [39]:
# Passing an integer for each index, the result is a scalar.

print('Rank 2 tensor \n',rank_2_tensor)
# Pull out a single value from a 2-rank tensor
print('Single value from a 2-rank tensor ',rank_2_tensor[1, 1].numpy())
# You can index using any combination of integers and slices:
# Get row and column tensors
print("Second row:", rank_2_tensor[1, :].numpy())
print("Second column:", rank_2_tensor[:, 1].numpy())
print("Last row:", rank_2_tensor[-1, :].numpy())
print("First item in last column:", rank_2_tensor[0, -1].numpy())
print("Skip the first row:")
print(rank_2_tensor[1:, :].numpy(), "\n")

Rank 2 tensor 
 tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
Single value from a 2-rank tensor  5.0
Second row: [4. 5. 6.]
Second column: [2. 5.]
Last row: [4. 5. 6.]
First item in last column: 3.0
Skip the first row:
[[4. 5. 6.]] 



In [46]:
# Here is an example with a 3-axis tensor:
nd_array =np.arange(30).reshape(3,2,5)
rank_3_tensor = tf.constant(nd_array)
print('Rank 3 tensor \n', rank_3_tensor)

Rank 3 tensor 
 tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int64)


Selecting the last feature across all locations in each example in the batch

<img src="https://www.tensorflow.org/guide/images/tensor/index1.png" />

In [47]:
# Selecting the last feature across all locations in each example in the batch
print('Selecting the last feature across all locations in each example in the batch')
print(rank_3_tensor[:,:,4])

Selecting the last feature across all locations in each example in the batch
tf.Tensor(
[[ 4  9]
 [14 19]
 [24 29]], shape=(3, 2), dtype=int64)


## Manipulating Shapes
Reshaping a tensor is of great utility.

In [49]:
# Shape returns a `TensorShape` object that shows the size along each axis
x = tf.constant([[1], [2], [3]])
print('shape of tensor',x.shape)
# # You can convert this object into a Python list, too
print('shape of tensor as a list',x.shape.as_list())

shape of tensor (3, 1)
shape of tensor as a list [3, 1]


You can reshape a tensor into a new shape. The tf.reshape operation is fast and cheap as the underlying data does not need to be duplicated.




In [53]:
# You can reshape a tensor to a new shape.
# Note that you're passing in a list
print('tensor before reshaping \n\n',x,'\n\nshape of tensor is ',x.shape)

reshaped = tf.reshape(x, [1,3])
print('\ntensor after reshaping \n\n',reshaped,'\n\nshape of tensor is ',reshaped.shape)

tensor before reshaping 

 tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32) 

shape of tensor is  (3, 1)

tensor after reshaping 

 tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32) 

shape of tensor is  (1, 3)


The data maintains its layout in memory and a new tensor is created, with the requested shape, pointing to the same data.

TensorFlow uses C-style "row-major" memory ordering, where incrementing the rightmost index corresponds to a single step in memory

If you flatten a tensor you can see what order it is laid out in memory.

In [54]:
print('3d tensor \n\n',rank_3_tensor.numpy())
print('\n3d tensor flattened \n\n',tf.reshape(rank_3_tensor, -1).numpy())

3d tensor 

 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]

3d tensor flattened 

 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


**Typically the only reasonable use of tf.reshape is to combine or split adjacent axes (or add/remove 1s)**.

For this 3x2x5 tensor, reshaping to (3x2)x5 or 3x(2x5) are both reasonable things to do, as the slices do not mix:

* Reshaping will "work" for any new shape with the same total number of elements, but it will not do anything useful if you do not respect the order of the axes.

* Swapping axes in tf.reshape does not work; you need tf.transpose for that.

In [57]:
print('Rank 3 Tensor \n\n',rank_3_tensor.numpy())
print('\n3x2x5 tensor, reshaping to (3x2)x5 \n',tf.reshape(rank_3_tensor, [3*2, 5]).numpy())
print('\n3x2x5 tensor, reshaping to 3x(2x5) \n',tf.reshape(rank_3_tensor, [3, 2*5]).numpy())

Rank 3 Tensor 

 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]

3x2x5 tensor, reshaping to (3x2)x5 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

3x2x5 tensor, reshaping to 3x(2x5) 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


**Some good reshapes.**<br>
<img src='https://www.tensorflow.org/guide/images/tensor/reshape-before.png' />
<br>
<img src='https://www.tensorflow.org/guide/images/tensor/reshape-good1.png' />
<br>
<img src='https://www.tensorflow.org/guide/images/tensor/reshape-good2.png' />


**Some bad reshapes.**<br>
<img src='https://www.tensorflow.org/guide/images/tensor/reshape-bad.png' />
<br>
<img src='https://www.tensorflow.org/guide/images/tensor/reshape-bad4.png' />
<br>
<img src='https://www.tensorflow.org/guide/images/tensor/reshape-bad2.png' />
<br>
You may run across not-fully-specified shapes. Either the shape contains a None (an axis-length is unknown) or the whole shape is None (the rank of the tensor is unknown).

Except for tf.RaggedTensor, such shapes will only occur in the context of TensorFlow's symbolic, graph-building APIs:

##  DTypes
To inspect a tf.Tensor's data type use the Tensor.dtype property.

When creating a tf.Tensor from a Python object you may optionally specify the datatype.

If you don't, TensorFlow chooses a datatype that can represent your data. TensorFlow converts Python integers to tf.int32 and Python floating point numbers to tf.float32. Otherwise TensorFlow uses the same rules NumPy uses when converting to arrays.

You can cast from type to type.


In [58]:
the_f64_tensor = tf.constant([2.2, 3.3, 4.4], dtype=tf.float64)
the_f16_tensor = tf.cast(the_f64_tensor, dtype=tf.float16)
# Now, cast to an uint8 and lose the decimal precision
the_u8_tensor = tf.cast(the_f16_tensor, dtype=tf.uint8)
print(the_u8_tensor)

tf.Tensor([2 3 4], shape=(3,), dtype=uint8)


## Broadcasting

In short, under certain conditions, smaller tensors are "stretched" automatically to fit larger tensors when running combined operations on them.

The simplest and most common case is when you attempt to multiply or add a tensor to a scalar. In that case, the scalar is broadcast to be the same shape as the other argument.


In [59]:
x = tf.constant([1, 2, 3])

y = tf.constant(2)
z = tf.constant([2, 2, 2])
# All of these are the same computation
print(tf.multiply(x, 2))
print(x * y)
print(x * z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


Likewise, axes with length 1 can be stretched out to match the other arguments. Both arguments can be stretched in the same computation.

In this case a 3x1 matrix is element-wise multiplied by a 1x4 matrix to produce a 3x4 matrix. Note how the leading 1 is optional: The shape of y is [4].




In [60]:
# These are the same computations
x = tf.reshape(x,[3,1])
y = tf.range(1, 5)
print(x, "\n")
print(y, "\n")
print(tf.multiply(x, y))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32) 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) 

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


A broadcasted add: a `[3, 1]` times a `[1, 4]` gives a `[3,4]`
<img src="https://www.tensorflow.org/guide/images/tensor/broadcasting.png"/>

In [61]:
x_stretch = tf.constant([[1, 1, 1, 1],
                         [2, 2, 2, 2],
                         [3, 3, 3, 3]])

y_stretch = tf.constant([[1, 2, 3, 4],
                         [1, 2, 3, 4],
                         [1, 2, 3, 4]])

print(x_stretch * y_stretch) 

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


**Most of the time, broadcasting is both time and space efficient, as the broadcast operation never materializes the expanded tensors in memory.**



In [62]:
x = tf.constant([1,2,3])
tf.broadcast_to(x, shape=[3,3])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]], dtype=int32)>

**Unlike a mathematical op, for example, broadcast_to does nothing special to save memory. Here, you are materializing the tensor**.

**The base tf.Tensor class requires tensors to be "rectangular"---that is, along each axis, every element is the same size**. However, there are specialized types of tensors that can handle different shapes:

* Ragged tensors 
* Sparse tensors 

## Ragged Tensors
A tensor with variable numbers of elements along some axis is called "ragged". Use `tf.ragged.RaggedTensor` for ragged data.

For example, This cannot be represented as a regular tensor:

A `tf.RaggedTensor`, shape: `[4, None]`

<img src='https://www.tensorflow.org/guide/images/tensor/ragged.png' />

**The shape of a tf.RaggedTensor will contain some axes with unknown lengths:**

In [64]:
ragged = tf.ragged.constant([[3, 1, 4, 1], [], [5, 9, 2], [6], []])
print('Ragged Tensor \n',ragged)
print('\nRagged Tensor shape \n',ragged.shape)

Ragged Tensor 
 <tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>

Ragged Tensor shape 
 (5, None)


## String tensors
`tf.string` is a dtype, which is to say you can represent data as strings (variable-length byte arrays) in tensors.

The strings are atomic and cannot be indexed the way Python strings are. The length of the string is not one of the axes of the tensor. 

Here is a scalar string tensor:

In [65]:
merc = tf.constant('TOTO WOLF')
print('string tensor', merc)

string tensor tf.Tensor(b'TOTO WOLF', shape=(), dtype=string)


**A vector of strings, shape: [3,]**
<img src='https://www.tensorflow.org/guide/images/tensor/strings.png' />

In [74]:
# If you have three string tensors of different lengths, this is OK.
benz = tf.constant(['TOTO WOLF','HAMILTON','BOTTAS'])
print('string tensor', benz)
# SHAPE -- string length is not included
print('shape ',benz.shape)

string tensor tf.Tensor([b'TOTO WOLF' b'HAMILTON' b'BOTTAS'], shape=(3,), dtype=string)
shape  (3,)


**the `b` prefix indicates that `tf.string` dtype is not a unicode string, but a `byte-string`.**


In [70]:
# If you pass unicode characters they are utf-8 encoded.
utf = tf.constant("🥳👍")
print('utf-8 encoded',utf)

utf-8 encoded tf.Tensor(b'\xf0\x9f\xa5\xb3\xf0\x9f\x91\x8d', shape=(), dtype=string)


In [72]:
# You can use split to split a string into a set of tensors
print(merc)
print(tf.strings.split(merc, sep=" "))

tf.Tensor(b'TOTO WOLF', shape=(), dtype=string)
tf.Tensor([b'TOTO' b'WOLF'], shape=(2,), dtype=string)


In [73]:
# ...but it turns into a `RaggedTensor` if you split up a tensor of strings,
# as each string might be split into a different number of parts.
print(tf.strings.split(benz))

<tf.RaggedTensor [[b'TOTO', b'WOLF'], [b'HAMILTON'], [b'BOTTAS']]>


**Three strings split, shape: [3, None]**
<img src='https://www.tensorflow.org/guide/images/tensor/string-split.png' />

In [78]:
text = tf.constant('1 2 3')
print('Tensor',text.numpy())
print('Type ',text.dtype)
split = tf.strings.split(text, sep=" ")
print('Tensor splited ',split.numpy())
num = tf.strings.to_number(split)
print('change string to number', num.numpy())
print('type ', num.dtype)

Tensor b'1 2 3'
Type  <dtype: 'string'>
Tensor splited  [b'1' b'2' b'3']
change string to number [1. 2. 3.]
type  <dtype: 'float32'>


**Although you can't use tf.cast to turn a string tensor into numbers, you can convert it into bytes, and then into numbers**.

In [79]:
byte_strings = tf.strings.bytes_split(tf.constant("Duck"))
byte_ints = tf.io.decode_raw(tf.constant("Duck"), tf.uint8)
print("Byte strings:", byte_strings)
print("Bytes:", byte_ints)

Byte strings: tf.Tensor([b'D' b'u' b'c' b'k'], shape=(4,), dtype=string)
Bytes: tf.Tensor([ 68 117  99 107], shape=(4,), dtype=uint8)


In [84]:
# Or split it up as unicode and then decode it
unicode_bytes = tf.constant("アヒル 🦆")
unicode_char_bytes = tf.strings.unicode_split(unicode_bytes, 'UTF-8')
unicode_vals = tf.strings.unicode_decode(unicode_char_bytes, 'UTF-8')
print('unicode', unicode_vals)

unicode <tf.RaggedTensor [[12450], [12498], [12523], [32], [129414]]>


## Sparse tensors
Sometimes, your data is sparse, like a very wide embedding space. 

* use `tf.sparse.SparseTensor`  to store sparse data efficiently.

A tf.SparseTensor, shape: `[3, 4]`

<img src='https://www.tensorflow.org/guide/images/tensor/sparse.png' />

In [87]:
sparse = tf.sparse.SparseTensor(indices=[[0,0],[1,2]], values=[1,2], dense_shape=[3,4])
print('sparse tensor \n\n',sparse)

# You can convert sparse tensors to dense
print('\n\nsparese to dense\n',tf.sparse.to_dense(sparse) )

sparse tensor 

 SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


sparese to dense
 tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
